version: "3.8"

services:
  express:
    container_name: cpa-api
    build:
      context: .
      dockerfile: Dockerfile # make sure your Dockerfile is at the root
    ports:
      - "2323:2323" # Assuming your app runs on port 2323 inside container

# # Networks
# networks:
#   app-network:
#     driver: bridge
# # Volumes
# volumes:
#   postgres_data:
#     driver: local
#   redis_data:
#     driver: local
#   pgadmin_data:
#     driver: local
